## FIRST LINE/ROW: Info & Status
# First param â”€â”Œ
[username]
format = " [â•­â”€$user]($style)@"
style_user = "bold green"
style_root = "bold green"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed red"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
# [directory]
# style = "purple"
# truncation_length = 0
# truncate_to_repo = true
# truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
disabled = true
# style = "white"
# ahead = "â‡¡${count}"
# diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
# behind = "â‡£${count}"
# deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï–‚ "
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"
disabled = true

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"
disabled = true

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"
disabled = true

# # Prompt: optional param 1
# [time]
# format = " ğŸ•™ $time($style)\n"
# time_format = "%T"
# style = "bright-white"
# disabled = true
# Prompt: param 2 â””â”€
[character]
success_symbol = " [â•°â”€Î»](bold green)"
error_symbol = " [â•°â”€Ã—](bold red)"
# use_symbol_for_status = true

# SYMBOLS
# [status]
# symbol = "ğŸ”´"
# format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
# map_symbol = true
# disabled = false

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "
ignore_base = false

[dart]
symbol = "î˜ "

[directory]
read_only = " ï ½"

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "
disabled = true

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ï¡š "

[meson]
symbol = "ï¨¶ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "

# format = "$all"

# [character]
# success_symbol = "[Î»](bold green)"
# error_symbol = "[Î»](bold red)"

# [aws]
# symbol = "îŒ½  "
# format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

# [cmake]
# format = '\[[$symbol($version)]($style)\]'

# [cmd_duration]
# format = '\[[$symbol$duration]($style)\]'

# [cobol]
# format = '\[[$symbol($version)]($style)\]'

# [conda]
# symbol = "ï„Œ "
# format = '\[[$symbol$environment]($style)\]'
# ignore_base = false

# [crystal]
# format = '\[[$symbol($version)]($style)\]'

# [dart]
# symbol = "î˜ "
# format = '\[[$symbol($version)]($style)\]'

# [deno]
# format = '\[[$symbol($version)]($style)\]'

# [directory]
# read_only = " ï ½"

# [docker_context]
# symbol = "ïŒˆ "
# format = '\[[$symbol$context]($style)\]'

# [dotnet]
# format = '\[[$symbol($version)(ğŸ¯ $tfm)]($style)\]'

# [elixir]
# symbol = "î‰µ "
# format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

# [elm]
# symbol = "î˜¬ "
# format = '\[[$symbol($version)]($style)\]'

# [erlang]
# format = '\[[$symbol($version)]($style)\]'

# [gcloud]
# format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

# [git_branch]
# symbol = "ï˜ "
# format = '\[[$symbol$branch]($style)\]'

# [git_status]
# format = '([\[$all_status$ahead_behind\]]($style))'

# [golang]
# symbol = "î˜§ "
# format = '\[[$symbol($version)]($style)\]'

# [helm]
# format = '\[[$symbol($version)]($style)\]'

# [hg_branch]
# symbol = "ï˜ "
# format = '\[[$symbol$branch]($style)\]'

# [java]
# symbol = "î‰– "
# format = '\[[$symbol($version)]($style)\]'

# [julia]
# symbol = "î˜¤ "
# format = '\[[$symbol($version)]($style)\]'

# [kotlin]
# format = '\[[$symbol($version)]($style)\]'

# [kubernetes]
# format = '\[[$symbol$context( \($namespace\))]($style)\]'

# [lua]
# format = '\[[$symbol($version)]($style)\]'

# [memory_usage]
# symbol = "ï¡š "
# format = '\[$symbol[$ram( | $swap)]($style)\]'

# [nim]
# symbol = "ïš¤ "
# format = '\[[$symbol($version)]($style)\]'

# [nix_shell]
# symbol = "ï‹œ "
# format = '\[[$symbol$state( \($name\))]($style)\]'

# [nodejs]
# format = '\[[$symbol($version)]($style)\]'

# [ocaml]
# format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

# [openstack]
# format = '\[[$symbol$cloud(\($project\))]($style)\]'

# [package]
# symbol = "ï£– "
# format = '\[[$symbol$version]($style)\]'

# [perl]
# symbol = "î© "
# format = '\[[$symbol($version)]($style)\]'

# [php]
# symbol = "î˜ˆ "
# format = '\[[$symbol($version)]($style)\]'

# [pulumi]
# format = '\[[$symbol$stack]($style)\]'

# [purescript]
# format = '\[[$symbol($version)]($style)\]'

# [python]
# symbol = "î˜† "
# format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

# [red]
# format = '\[[$symbol($version)]($style)\]'

# [ruby]
# symbol = "îˆ¾ "
# format = '\[[$symbol($version)]($style)\]'

# [rust]
# symbol = "î¨ "
# format = '\[[$symbol($version)]($style)\]'

# [scala]
# symbol = "îœ· "
# format = '\[[$symbol($version)]($style)\]'

# [shlvl]
# symbol = "ï„  "

# [sudo]
# format = '\[[as $symbol]\]'

# [swift]
# symbol = "ï¯£ "
# format = '\[[$symbol($version)]($style)\]'

# [terraform]
# format = '\[[$symbol$workspace]($style)\]'

# [time]
# format = '\[[$time]($style)\]'

# [username]
# format = '\[[$user]($style)\]'

# [vagrant]
# format = '\[[$symbol($version)]($style)\]'

# [vlang]
# format = '\[[$symbol($version)]($style)\]'

# [zig]
# format = '\[[$symbol($version)]($style)\]'

